In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("D:\desktop\eda\IPL DATA SET.csv")
df

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,2017,Hyderabad,2017-04-05,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
1,2,2017,Pune,2017-04-06,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN
2,3,2017,Rajkot,2017-04-07,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,NaN
3,4,2017,Indore,2017-04-08,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN
4,5,2017,Bangalore,2017-04-08,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
751,11347,2019,Mumbai,05/05/19,Kolkata Knight Riders,Mumbai Indians,Mumbai Indians,field,normal,0,Mumbai Indians,0,9,HH Pandya,Wankhede Stadium,Nanda Kishore,O Nandan,S Ravi
752,11412,2019,Chennai,07/05/19,Chennai Super Kings,Mumbai Indians,Chennai Super Kings,bat,normal,0,Mumbai Indians,0,6,AS Yadav,M. A. Chidambaram Stadium,Nigel Llong,Nitin Menon,Ian Gould
753,11413,2019,Visakhapatnam,08/05/19,Sunrisers Hyderabad,Delhi Capitals,Delhi Capitals,field,normal,0,Delhi Capitals,0,2,RR Pant,ACA-VDCA Stadium,NaN,NaN,NaN
754,11414,2019,Visakhapatnam,10/05/19,Delhi Capitals,Chennai Super Kings,Chennai Super Kings,field,normal,0,Chennai Super Kings,0,6,F du Plessis,ACA-VDCA Stadium,Sundaram Ravi,Bruce Oxenford,Chettithody Shamshuddin
755,11415,2019,Hyderabad,12/05/19,Mumbai Indians,Chennai Super Kings,Mumbai Indians,bat,normal,0,Mumbai Indians,1,0,JJ Bumrah,Rajiv Gandhi Intl. Cricket Stadium,Nitin Menon,Ian Gould,Nigel Llong

In [4]:
# 1.FIND TOP 10 ROWS OF A DATASET
df.head(10)

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,2017,Hyderabad,2017-04-05,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
1,2,2017,Pune,2017-04-06,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN
2,3,2017,Rajkot,2017-04-07,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,NaN
3,4,2017,Indore,2017-04-08,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN
4,5,2017,Bangalore,2017-04-08,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN,NaN
5,6,2017,Hyderabad,2017-04-09,Gujarat Lions,Sunrisers Hyderabad,Sunrisers Hyderabad,field,normal,0,Sunrisers Hyderabad,0,9,Rashid Khan,"Rajiv Gandhi International Stadium, Uppal",A Deshmukh,NJ Llong,NaN
6,7,2017,Mumbai,2017-04-09,Kolkata Knight Riders,Mumbai Indians,Mumbai Indians,field,normal,0,Mumbai Indians,0,4,N Rana,Wankhede Stadium,Nitin Menon,CK Nandan,NaN
7,8,2017,Indore,2017-04-10,Royal Challengers Bangalore,Kings XI Punjab,Royal Challengers Bangalore,bat,normal,0,Kings XI Punjab,0,8,AR Patel,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN
8,9,2017,Pune,2017-04-11,Delhi Daredevils,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Delhi Daredevils,97,0,SV Samson,Maharashtra Cricket Association Stadium,AY Dandekar,S Ravi,NaN
9,10,2017,Mumbai,2017-04-12,Sunrisers Hyderabad,Mumbai Indians,Mumbai Indians,field,normal,0,Mumbai Indians,0,4,JJ Bumrah,Wankhede Stadium,Nitin Menon,CK Nandan,NaN

In [6]:
# 2.CHECK FOR THE INFORMATION ABOUT A DATA FRAME
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 756 entries, 0 to 755
Data columns (total 18 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               756 non-null    int64
 1   season           756 non-null    int64
 2   city             749 non-null    object
 3   date             756 non-null    object
 4   team1            756 non-null    object
 5   team2            756 non-null    object
 6   toss_winner      756 non-null    object
 7   toss_decision    756 non-null    object
 8   result           756 non-null    object
 9   dl_applied       756 non-null    int64
 10  winner           752 non-null    object
 11  win_by_runs      756 non-null    int64
 12  win_by_wickets   756 non-null    int64
 13  player_of_match  752 non-null    object
 14  venue            756 non-null    object
 15  umpire1          754 non-null    object
 16  umpire2          754 non-null    object
 17  umpire3          119 non-null    object
dtypes: int64(5), object(13)
memory usage: 106.4+ KB

In [9]:
# 3.CHECK THE SHAPE OF A DATASET
df.shape

(756, 18)

In [16]:
# 4.FIND OUT THE NAN VALUES
df.isnull().sum().sum()

656

In [18]:
# 5.CHECK FOR STATISTICAL INFORMATION ABOUT DATA SET
df.describe()

                 id       season  dl_applied  win_by_runs  win_by_wickets
count    756.000000   756.000000  756.000000   756.000000      756.000000
mean    1792.178571  2013.444444    0.025132    13.283069        3.350529
std     3464.478148     3.366895    0.156630    23.471144        3.387963
min        1.000000  2008.000000    0.000000     0.000000        0.000000
25%      189.750000  2011.000000    0.000000     0.000000        0.000000
50%      378.500000  2013.000000    0.000000     0.000000        4.000000
75%      567.250000  2016.000000    0.000000    19.000000        6.000000
max    11415.000000  2019.000000    1.000000   146.000000       10.000000

In [20]:
# 6.HOW MANY MATCHES WERE PLAYED IN TOTAL ACCORDING TO A DATASET.
len(df)

756

In [29]:
# 7.HOW MANY IPL SEASONS ARE WE USING TO ANALYZE.
SEASONS = df['season'].unique()
len(SEASONS)

12

In [37]:
# 8.WHICH IPL TEAM WON BY SCORING THE MAXIMUM RUNS?
# df.groupby('winner')['win_by_runs'].max()
df.groupby('winner')['win_by_runs'].max().idxmax() # idxmax = to show the maximum no of id 
# df.groupby('winner')['win_by_runs'].max().max()   # to show maximum number of amount

'Mumbai Indians'

In [47]:
# 9.WHICH IPL TEAM WON BY CONSUMING MAXIMUM WICKETS?
df.groupby('winner')['win_by_wickets'].max().idxmax()

'Chennai Super Kings'

In [50]:
# 10.WHICH IPL TEAM WON BY CONSUMING MINIMUM WICKETS?
df.groupby('winner')['win_by_wickets'].min().idxmin()

'Chennai Super Kings'

In [55]:
df.groupby(['winner','win_by_wickets']) # this is allowed when only we made group by 
                                        # it is not allowed when we give a arragument like ... .min() , .idxmax()

In [57]:
# 11.WHICH SEASON CONSISTED OF THE HIGHEST NUMBER OF MATCHES EVER PLAYED?
df.groupby('season')['date'].count().idxmax()

2013

In [62]:
# 12.WHICH IS THE MOST SUCCESSFUL IPL TEAM WITH ALL THE DATA AT A HAND?
df.groupby('winner')['winner'].count().idxmax()

'Mumbai Indians'

In [65]:
# 13.WHAT IS THE PROBABLITY OF WINNING A MATCH IF THE TOSS WAS WON?
df.groupby('winner')['toss_winner'].count().sum()

752

In [74]:
#Q-13 - WHAT IS THE PROBABLITY OF WINNING A MATCH IF THE TOSS WAS WON?
total_toss_won = df['toss_winner'].count()
print(total_toss_won)
# Count the number of matches won after winning the toss
matches_won_after_toss_won = df[(df['toss_winner'] == df['winner'])].shape[0]
print(matches_won_after_toss_won)
# Calculate the probability
probability = (matches_won_after_toss_won / total_toss_won) * 100
print("Probability of Winning after Winning Toss:", probability)

756
393
Probability of Winning after Winning Toss: 51.98412698412699

In [77]:
# 14.CHECK FOR HIGHEST WINS BY TEAMS PER SEASON
df.groupby('winner')['season'].max().idxmax()

'Chennai Super Kings'

In [85]:
# 15.CHECK FOR MAN OF THE MATCH --HIGHEST TO LOWEST(IN WON MATCHES)
df.groupby('winner')['player_of_match'].count()

winner
Chennai Super Kings            100
Deccan Chargers                 29
Delhi Capitals                  10
Delhi Daredevils                67
Gujarat Lions                   13
Kings XI Punjab                 82
Kochi Tuskers Kerala             6
Kolkata Knight Riders           92
Mumbai Indians                 109
Pune Warriors                   12
Rajasthan Royals                75
Rising Pune Supergiant          10
Rising Pune Supergiants          5
Royal Challengers Bangalore     84
Sunrisers Hyderabad             58
Name: player_of_match, dtype: int64

In [87]:
# 16.IN WHICH CITY WERE THE NUMBER OF MATCHES PLAYED?
df.groupby('city')['city'].count()

city
Abu Dhabi           7
Ahmedabad          12
Bangalore          66
Bengaluru          14
Bloemfontein        2
Cape Town           7
Centurion          12
Chandigarh         46
Chennai            57
Cuttack             7
Delhi              74
Dharamsala          9
Durban             15
East London         3
Hyderabad          64
Indore              9
Jaipur             47
Johannesburg        8
Kanpur              4
Kimberley           3
Kochi               5
Kolkata            77
Mohali             10
Mumbai            101
Nagpur              3
Port Elizabeth      7
Pune               38
Raipur              6
Rajkot             10
Ranchi              7
Sharjah             6
Visakhapatnam      13
Name: city, dtype: int64

In [88]:
df.groupby('city')['city'].count().idxmax()

'Mumbai'